options(repos=structure(BiocManager::repositories()))
# packrat::init()
# packrat::on()
packrat::set_opts(vcs.ignore.lib=T)
packrat::set_opts(vcs.ignore.src=T)
packrat::status()
packrat::snapshot()
packrat::restore()
# packrat::clean()
# packrat::off()
